/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package Vistas_registros;

import Modelo_clases.bicicleta;
import Utilidades.Utilidades;
import basededatos_Conexion.Conexion;
import java.awt.Color;
import java.util.ArrayList;
import javax.swing.JOptionPane;


/**
 *
 * @author ikerr
 */
public class Ventana_bicicleta extends javax.swing.JDialog {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Ventana_bicicleta.class.getName());

    /**
     * Creates new form Ventana_bicicleta
     */
    public Ventana_bicicleta(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Conexion.conectar();
        Conexion.cargasComboProveedores(comboProveedor3);
        Conexion.cargasComboEstados(comboEstado3);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        campoCodigo3 = new javax.swing.JTextField();
        campoMarca3 = new javax.swing.JTextField();
        campoAñoComp3 = new javax.swing.JTextField();
        comboProveedor3 = new javax.swing.JComboBox<>();
        campoAñocadu = new javax.swing.JTextField();
        campoAutonomia = new javax.swing.JTextField();
        comboEstado3 = new javax.swing.JComboBox<>();
        jButton4 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Patin");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos registro", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 0, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        jPanel5.setForeground(new java.awt.Color(0, 204, 204));
        jPanel5.setOpaque(false);

        jLabel30.setForeground(new java.awt.Color(255, 255, 255));
        jLabel30.setText("Codigo");

        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Marca");

        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Proveedor");

        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("Año de compra");

        jLabel34.setForeground(new java.awt.Color(255, 255, 255));
        jLabel34.setText("Estado");

        jLabel35.setForeground(new java.awt.Color(255, 255, 255));
        jLabel35.setText("Año caducidad bateria");

        jLabel36.setForeground(new java.awt.Color(255, 255, 255));
        jLabel36.setText("Autonomia bateria");

        campoCodigo3.setName("codigo"); // NOI18N

        campoMarca3.setName("marca"); // NOI18N

        campoAñoComp3.setName("añocompra"); // NOI18N

        comboProveedor3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboProveedor3.setName("proveedor"); // NOI18N

        campoAñocadu.setName("añocaducbateria"); // NOI18N

        campoAutonomia.setName("autbateria"); // NOI18N

        comboEstado3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione" }));
        comboEstado3.setName("estado"); // NOI18N

        jButton4.setText("Alta");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel31, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel33, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel35)
                            .addComponent(jLabel36))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(comboEstado3, 0, 131, Short.MAX_VALUE)
                            .addComponent(campoAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoAñocadu, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(comboProveedor3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(campoAñoComp3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(campoCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(90, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel30)
                    .addComponent(campoCodigo3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel31)
                    .addComponent(campoMarca3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel32)
                    .addComponent(comboProveedor3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(campoAñoComp3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel34)
                    .addComponent(comboEstado3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel35)
                    .addComponent(campoAñocadu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel36)
                    .addComponent(campoAutonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jButton4)
                .addGap(17, 17, 17))
        );

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bicicleta_2.png"))); // NOI18N
        jLabel11.setText("jLabel11");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 377, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel11)))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
registrar();       
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Ventana_bicicleta dialog = new Ventana_bicicleta(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField campoAutonomia;
    private javax.swing.JTextField campoAñoComp3;
    private javax.swing.JTextField campoAñocadu;
    private javax.swing.JTextField campoCodigo3;
    private javax.swing.JTextField campoMarca3;
    private javax.swing.JComboBox<String> comboEstado3;
    private javax.swing.JComboBox<String> comboProveedor3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    // End of variables declaration//GEN-END:variables

ArrayList<bicicleta> Bicicletas = new ArrayList<>();

public void registrar() {
    if (Utilidades.compruebaCampoVacio(campoCodigo3)) {
        Utilidades.lanzaAlertaVacio(campoCodigo3);
    } else if (comprobarCodigo(campoCodigo3.getText())) {
        JOptionPane.showMessageDialog(this, "Este código ya fue registrado");
        campoCodigo3.setText("");
        campoCodigo3.setBackground(Color.red);
    } else if (Utilidades.compruebaCampoVacio(campoMarca3)) {
        Utilidades.lanzaAlertaVacio(campoMarca3);
    } else if (comboProveedor3.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un proveedor");
        comboProveedor3.requestFocus();
    } else if (Utilidades.compruebaCampoVacio(campoAñoComp3)) {
        Utilidades.lanzaAlertaVacio(campoAñoComp3);
    } else if (comboEstado3.getSelectedIndex() == 0) {
        JOptionPane.showMessageDialog(this, "Debe seleccionar un estado");
        comboEstado3.requestFocus();
    } else if (Utilidades.compruebaCampoVacio(campoAñocadu)) {
        Utilidades.lanzaAlertaVacio(campoAñocadu);
    } else if (Utilidades.compruebaCampoVacio(campoAutonomia)) {
        Utilidades.lanzaAlertaVacio(campoAutonomia);
    } else {
        try {
            String codigo = campoCodigo3.getText().trim();
            String marca = campoMarca3.getText().trim();
            String proveedor = comboProveedor3.getSelectedItem().toString();
            int anioCompra = Integer.parseInt(campoAñoComp3.getText().trim());
            String estado = comboEstado3.getSelectedItem().toString();
            int caducidadLlantas = Integer.parseInt(campoAñocadu.getText().trim());
            double autonomiaBateria = Double.parseDouble(campoAutonomia.getText().trim());
            
            bicicleta b = new bicicleta(caducidadLlantas, autonomiaBateria, codigo,
                                       marca, proveedor, anioCompra, estado);
            
            Bicicletas.add(b);
            
            JOptionPane.showMessageDialog(this, "Bicicleta registrada exitosamente", 
                                         "Registro exitoso", JOptionPane.INFORMATION_MESSAGE);
            
            limpiarFormulario();
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Error en los datos numéricos. Verifique que:\n" +
                                         "- Año de compra sea un número entero\n" +
                                         "- Año caducidad llantas sea un número entero\n" +
                                         "- Autonomía de la batería sea un número válido",
                                         "Error de formato", JOptionPane.ERROR_MESSAGE);
        }
    }
}

public boolean comprobarCodigo(String codigoNuevo) {
    for (bicicleta b : Bicicletas) {
        if (b.getCii().equalsIgnoreCase(codigoNuevo)) {
            return true;
        }
    }
    return false;
}

public void limpiarFormulario() {
    campoCodigo3.setText("");
    campoMarca3.setText("");
    comboProveedor3.setSelectedIndex(0);
    campoAñoComp3.setText("");
    comboEstado3.setSelectedIndex(0);
    campoAñocadu.setText("");
    campoAutonomia.setText("");
    
    campoCodigo3.setBackground(Color.WHITE);
    campoMarca3.setBackground(Color.WHITE);
    campoAñoComp3.setBackground(Color.WHITE);
    campoAñocadu.setBackground(Color.WHITE);
    campoAutonomia.setBackground(Color.WHITE);
    
    campoCodigo3.requestFocus();
}

private void btnAltaActionPerformed(java.awt.event.ActionEvent evt) {
    registrar();
}
}
